{{- $root := . -}}
{{- range $component, $config := .Values.components }}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plaid-quickstart.fullname" $root }}-{{ $component }}
  labels:
    {{- include "plaid-quickstart.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  {{- if not $config.autoscaling.enabled }}
  replicas: {{ $config.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plaid-quickstart.selectorLabels" $root | nindent 6 }}
  template:
    metadata:
      {{- with $config.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plaid-quickstart.labels" $root | nindent 8 }}
        {{- with $config.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $config.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plaid-quickstart.serviceAccountName" $root }}
      securityContext:
        {{- toYaml $config.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $root.Chart.Name }}
          securityContext:
            {{- toYaml $config.securityContext | nindent 12 }}
          image: "{{ $config.image.repository }}:{{ $config.image.tag | default $root.Chart.AppVersion }}"
          imagePullPolicy: {{ $config.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $config.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml $config.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $config.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml $config.resources | nindent 12 }}
          {{- with $config.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $config.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $config.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $config.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $config.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
