{{- $root := . -}}
{{- range $component, $config := .Values.components }}

{{- if $config.autoscaling.enabled }}
---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "plaid-quickstart.fullname" $root }}-{{ $component }}
  labels:
    {{- include "plaid-quickstart.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "plaid-quickstart.fullname" $root }}-{{ $component }}
  minReplicas: {{ $config.autoscaling.minReplicas }}
  maxReplicas: {{ $config.autoscaling.maxReplicas }}
  metrics:
    {{- if $config.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $config.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if $config.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $config.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}

{{- end }}
