{{- range $component, $config := .Values.components }}
{{- if $config.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "plaid-quickstart.serviceAccountName" (dict "root" $ "component" $component) }}
  labels:
    {{- include "plaid-quickstart.labels" $ | nindent 4 }}
  {{- with $config.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $config.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
